//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Accouting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public int ROOM_ID { get; set; }
        public string ROOM_NAME { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
