
-- setting for database 
create database hrms;
use  hrms ;
set dateformat dmy

CREATE TABLE ROOM (
	ROOM_ID INT IDENTITY(1,1) PRIMARY KEY,
	ROOM_NUMBER VARCHAR(20)
);

CREATE TABLE DEPARTMENT (
	DEPT_ID INT IDENTITY (1, 1) PRIMARY KEY,
	DEPT_NAME VARCHAR(200),
	ROOM_ID INT 
	FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

CREATE TABLE ROLE(
	ROLE_ID INT IDENTITY(1,1) PRIMARY KEY,
	PERMISSION INT ,
	ROLE_NAME VARCHAR(30),
	ROLE_DESC TEXT,
	DEPT_ID INT,
	FOREIGN KEY( DEPT_ID ) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID INT IDENTITY(1,1) PRIMARY KEY  ,
	NAME VARCHAR(100),
	ID INT UNIQUE,
	AGE INT ,
	BLOODTYPE VARCHAR(20),
	EMAIL VARCHAR(40), 
	PHONE VARCHAR(20),
	DEPT_ID INT  ,
	ROLE_ID INT ,
	BIRTH_DATE DATE,
	FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID),
	FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);


CREATE TABLE TIMEKEEPING (
	TIMEKEEPING_ID INT IDENTITY (1, 1) PRIMARY KEY,
	EMPLOYEE_ID INT ,
	NUMBER_OF_WORK_DAY INT, 
	NUMBER_OF_ABSENT_DAY INT ,
	NUMBER_OF_OVERTIME_DAY INT
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),

);

CREATE TABLE TIMEKEEPING_DETAIL (
	TIMEKEEPING_DETAIL_ID INT IDENTITY(1, 1 ) PRIMARY KEY,
	TIMEKEEPING_ID INT ,
	CHECK_DATE DATE,
	CHECK_TIME TIME,
	EMPLOYEE_ID INT ,
	FOREIGN KEY(EMPLOYEE_ID ) REFERENCES EMPLOYEE(EMPLOYEE_ID),
	FOREIGN KEY(TIMEKEEPING_ID) REFERENCES TIMEKEEPING(TIMEKEEPING_ID)
);

CREATE TABLE SALARY(
	SALARY_ID INT IDENTITY(1, 1) PRIMARY KEY,
	WAGE BIGINT,
	TAX BIGINT,
	TOTAL_SALARY BIGINT,
	COEFFICIENT FLOAT , 
	INSURANCE BIGINT, 
	EMPLOYEE_ID INT ,
	DATE_START DATE, 
	DATE_END DATE,
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);


--insert data

begin --room  
SELECT * FROM ROOM
INSERT INTO ROOM(ROOM_NUMBER)
VALUES ('PHONGSO1');

INSERT INTO ROOM(ROOM_NUMBER)
VALUES ('PHONGSO2');

INSERT INTO ROOM(ROOM_NUMBER)
VALUES ('PHONGSO3');
SELECT * FROM ROOM

end;

begin -- department 
SELECT * FROM DEPARTMENT;
INSERT INTO DEPARTMENT (DEPT_NAME, ROOM_ID)
VALUES ('PHONG NHAN SU 1'  ,1 );

INSERT INTO DEPARTMENT (DEPT_NAME, ROOM_ID)
VALUES ('PHONG NHAN SU 2'  ,1 );

INSERT INTO DEPARTMENT (DEPT_NAME, ROOM_ID)
VALUES ('PHONG KE TOAN 1'  ,2 );

INSERT INTO DEPARTMENT (DEPT_NAME, ROOM_ID)
VALUES ('PHONG KE TOAN 3'  ,3 );
SELECT * FROM DEPARTMENT;
end;

begin -- role 
SELECT * FROM ROLE
INSERT INTO ROLE( PERMISSION , ROLE_NAME, ROLE_DESC , DEPT_ID)
VALUES (0, 'NhanVienVanPhong' , '...', 1);

INSERT INTO ROLE( PERMISSION , ROLE_NAME, ROLE_DESC , DEPT_ID)
VALUES (1, 'Ke toan' , '...', 1);

INSERT INTO ROLE( PERMISSION , ROLE_NAME, ROLE_DESC , DEPT_ID)
VALUES (0, 'NhanVienVanPhong' , '...', 2);

INSERT INTO ROLE( PERMISSION , ROLE_NAME, ROLE_DESC , DEPT_ID)
VALUES (0, 'NhanVienVanPhong' , '...', 2);

INSERT INTO ROLE( PERMISSION , ROLE_NAME, ROLE_DESC , DEPT_ID)
VALUES (0, 'NhanVienVanPhong' , '...', 2);

INSERT INTO ROLE( PERMISSION , ROLE_NAME, ROLE_DESC , DEPT_ID)
VALUES (2, 'Truong phong' , '...', 2);

INSERT INTO ROLE( PERMISSION , ROLE_NAME, ROLE_DESC , DEPT_ID)
VALUES (0, 'NhanVienVanPhong' , '...', 3);

INSERT INTO ROLE( PERMISSION , ROLE_NAME, ROLE_DESC , DEPT_ID)
VALUES (0, 'NhanVienVanPhong' , '...', 3)

INSERT INTO ROLE( PERMISSION , ROLE_NAME, ROLE_DESC , DEPT_ID)
VALUES (0, 'NhanVienVanPhong' , '...', 3);
SELECT * FROM ROLE
end;

begin -- employee 

SELECT * FROM EMPLOYEE;
INSERT INTO EMPLOYEE (ID , NAME , AGE, BLOODTYPE, EMAIL, PHONE , DEPT_ID , ROLE_ID )
VALUES ( 10001, 'NGUYEN VAN A' ,22, 'AB' , 'A@gmail.com', '020232323', 1,1);

INSERT INTO EMPLOYEE (ID , NAME , AGE, BLOODTYPE, EMAIL, PHONE , DEPT_ID , ROLE_ID )
VALUES ( 100301, 'NGUYEN VAN B' ,32, 'BS' , 'B@gmail.com', '011121212', 2,2);

INSERT INTO EMPLOYEE (ID , NAME , AGE, BLOODTYPE, EMAIL, PHONE , DEPT_ID , ROLE_ID )
VALUES ( 23232, 'NGUYEN VAN C' ,34, 'B+' , 'C@gmail.com', '0999212', 2,3);

SELECT NAME , DEPT_NAME, ROLE_NAME 
FROM( EMPLOYEE INNER JOIN ROLE 
ON EMPLOYEE.ROLE_ID = ROLE.ROLE_ID ) 
INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;


end;

begin -- timekeeping 
SELECT * FROM TIMEKEEPING;

INSERT INTO TIMEKEEPING (EMPLOYEE_ID, NUMBER_OF_WORK_DAY, 
NUMBER_OF_ABSENT_DAY, 
NUMBER_OF_OVERTIME_DAY)
VALUES ( 1, 20, 2, 8);

INSERT INTO TIMEKEEPING (EMPLOYEE_ID, NUMBER_OF_WORK_DAY, 
NUMBER_OF_ABSENT_DAY, 
NUMBER_OF_OVERTIME_DAY)
VALUES ( 2, 30, 0, 10);

INSERT INTO TIMEKEEPING (EMPLOYEE_ID, NUMBER_OF_WORK_DAY, 
NUMBER_OF_ABSENT_DAY, 
NUMBER_OF_OVERTIME_DAY)
VALUES ( 3, 20, 4, 20);
end;

begin -- timekeeping detail 

SELECT * FROM TIMEKEEPING_DETAIL;

-- employee1
INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '29-1-2018' ,'12:13', 1);

INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '1-2-2018' ,'10:13', 1);

INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '2-2-2018' ,'11:13', 1);

INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '3-2-2018' ,'1:13', 1);

-- employee2
INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '29-1-2018' ,'12:13', 2);

INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '1-2-2018' ,'10:13', 2);

INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '2-2-2018' ,'11:13', 2);

INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '3-2-2018' ,'1:13', 2);


-- employee3
INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '29-1-2018' ,'12:13', 3);

INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '1-2-2018' ,'10:13', 3);

INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '2-2-2018' ,'11:13', 3);

INSERT INTO TIMEKEEPING_DETAIL
(TIMEKEEPING_ID, CHECK_DATE, CHECK_TIME, EMPLOYEE_ID)
VALUES( 1, '3-2-2018' ,'1:13', 3);



end;

begin -- salary 
SELECT * FROM SALARY;

-- employee1
INSERT INTO SALARY(WAGE, TAX, TOTAL_SALARY, COEFFICIENT , INSURANCE, DATE_START, DATE_END,  EMPLOYEE_ID)
VALUES (111, 11, 11111, 0.1, 111 ,'1-1-2018', '1-2-2018', 1);

INSERT INTO SALARY(WAGE, TAX, TOTAL_SALARY, COEFFICIENT , INSURANCE, DATE_START, DATE_END,  EMPLOYEE_ID)
VALUES (111, 11, 11111, 0.1, 111 ,'1-2-2018', '1-3-2018', 1);


INSERT INTO SALARY(WAGE, TAX, TOTAL_SALARY, COEFFICIENT , INSURANCE, DATE_START, DATE_END,  EMPLOYEE_ID)
VALUES (111, 11, 11111, 0.1, 111 ,'1-3-2018', '1-4-2018', 1);


-- employee2
INSERT INTO SALARY(WAGE, TAX, TOTAL_SALARY, COEFFICIENT , INSURANCE, DATE_START, DATE_END,  EMPLOYEE_ID)
VALUES (22, 23, 2322, 0.2, 111 ,'1-1-2018', '1-2-2018', 2);

INSERT INTO SALARY(WAGE, TAX, TOTAL_SALARY, COEFFICIENT , INSURANCE, DATE_START, DATE_END,  EMPLOYEE_ID)
VALUES (12, 1331, 32323, 0.9, 221,'1-2-2018', '1-3-2018', 2);


INSERT INTO SALARY(WAGE, TAX, TOTAL_SALARY, COEFFICIENT , INSURANCE, DATE_START, DATE_END,  EMPLOYEE_ID)
VALUES (90, 232, 32322, 1.1, 1111 ,'1-3-2018', '1-4-2018', 2);


-- employee3
INSERT INTO SALARY(WAGE, TAX, TOTAL_SALARY, COEFFICIENT , INSURANCE, DATE_START, DATE_END,  EMPLOYEE_ID)
VALUES (34, 44, 4444, 3.2, 32,'1-8-2018', '1-9-2018', 3);
end;



--add employee gender
ALTER TABLE EMPLOYEE 
ADD GENDER NVARCHAR(10
);


UPDATE EMPLOYEE
SET GENDER ='Male';

-- add employee citizenship
ALTER TABLE EMPLOYEE 
ADD CITIZENSHIP NVARCHAR(100);

UPDATE EMPLOYEE
SET CITIZENSHIP = 'Korean';