//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMEKEEPING_DETAIL
    {
        public int TIMEKEEPING_DETAIL_ID { get; set; }
        public Nullable<int> TIMEKEEPING_ID { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public Nullable<System.TimeSpan> CHECK_TIME { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual TIMEKEEPING TIMEKEEPING { get; set; }
    }
}
